// Code generated by hertz generator.

package main

import (
	"context"
	"os"
	"time"

	"github.com/MoScenix/douyin-mall-backend/app/frontend/biz/router"
	futils "github.com/MoScenix/douyin-mall-backend/app/frontend/biz/utils"
	"github.com/MoScenix/douyin-mall-backend/app/frontend/conf"
	"github.com/MoScenix/douyin-mall-backend/app/frontend/infra/rpc"
	"github.com/MoScenix/douyin-mall-backend/app/frontend/middleware"
	"github.com/MoScenix/douyin-mall-backend/common/mtl"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	"github.com/hertz-contrib/pprof"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/redis"
	"github.com/joho/godotenv"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
)

func main() {
	// init dal
	// dal.Init()
	godotenv.Load()
	mtl.InitMetric("frontend", conf.GetConf().Hertz.MetricsPort, conf.GetConf().Registry.RegistryAddress[0])
	rpc.Init()
	address := conf.GetConf().Hertz.Address
	h := server.New(server.WithHostPorts(address))

	registerMiddleware(h)

	// add a ping route to test
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})

	router.GeneratedRegister(h)
	h.LoadHTMLGlob("template/*")
	h.Static("/template", "./template")
	h.Static("/static", "./")
	h.GET("/sign-in", func(c context.Context, ctx *app.RequestContext) {
		data := utils.H{
			"title": "Sign in",
			"next":  string(ctx.GetHeader("Referer")),
		}
		ctx.HTML(consts.StatusOK, "sign-in", futils.WarpResponse(c, ctx, data))
	})
	h.GET("/sign-up", func(c context.Context, ctx *app.RequestContext) {
		data := utils.H{
			"title": "Sign up",
			"next":  string(ctx.GetHeader("Referer")),
		}
		ctx.HTML(consts.StatusOK, "sign-up", futils.WarpResponse(c, ctx, data))
	})
	h.GET("/about", func(c context.Context, ctx *app.RequestContext) {
		data := utils.H{
			"title": "About",
		}
		ctx.HTML(consts.StatusOK, "about", futils.WarpResponse(c, ctx, data))
	})
	h.Spin()
}

func registerMiddleware(h *server.Hertz) {
	store, err := redis.NewStore(100, "tcp", conf.GetConf().Redis.Address, "", []byte(os.Getenv("SESSION_SECRET")))
	if err != nil {
		panic(err)
	}
	store.Options(sessions.Options{MaxAge: 86400, Path: "/"})
	rs, err := redis.GetRedisStore(store)
	if err == nil {
		rs.SetSerializer(sessions.JSONSerializer{})
	}
	h.Use(sessions.New("moscenix", store))
	// log
	logger := hertzlogrus.NewLogger()
	hlog.SetLogger(logger)
	hlog.SetLevel(conf.LogLevel())
	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS: zapcore.AddSync(&lumberjack.Logger{
			Filename:   conf.GetConf().Hertz.LogFileName,
			MaxSize:    conf.GetConf().Hertz.LogMaxSize,
			MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
			MaxAge:     conf.GetConf().Hertz.LogMaxAge,
		}),
		FlushInterval: time.Minute,
	}
	hlog.SetOutput(asyncWriter)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		asyncWriter.Sync()
	})

	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// access log
	if conf.GetConf().Hertz.EnableAccessLog {
		h.Use(accesslog.New())
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())
	middleware.Register(h)
}
