# docker_files/DockerFile.user
FROM golang:1.25.5

WORKDIR /usr/src/gomall

ENV GOPROXY=https://goproxy.cn,https://proxy.golang.org,direct
ENV GOSUMDB=sum.golang.google.cn

COPY app/orders/go.mod app/orders/go.sum ./app/orders/
COPY rpc_gen ./rpc_gen
COPY common ./common

RUN cd app/orders && go mod download && go mod verify

COPY app/orders ./app/orders

RUN cd app/orders && go build -v -o server

WORKDIR /usr/src/gomall/app/orders
EXPOSE 8080
CMD ["./server"]
