// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "github.com/MoScenix/douyin-mall-backend/app/frontend/biz/router/auth"
	cart "github.com/MoScenix/douyin-mall-backend/app/frontend/biz/router/cart"
	home "github.com/MoScenix/douyin-mall-backend/app/frontend/biz/router/home"
	order "github.com/MoScenix/douyin-mall-backend/app/frontend/biz/router/order"
	product "github.com/MoScenix/douyin-mall-backend/app/frontend/biz/router/product"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	cart.Register(r)

	order.Register(r)

	product.Register(r)

	auth.Register(r)

	home.Register(r)
}
