// Code generated by Kitex v0.9.1. DO NOT EDIT.

package ordersservice

import (
	"context"
	"errors"
	orders "github.com/MoScenix/douyin-mall-backend/rpc_gen/kitex_gen/orders"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetOrders": kitex.NewMethodInfo(
		getOrdersHandler,
		newGetOrdersArgs,
		newGetOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddOrder": kitex.NewMethodInfo(
		addOrderHandler,
		newAddOrderArgs,
		newAddOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	ordersServiceServiceInfo                = NewServiceInfo()
	ordersServiceServiceInfoForClient       = NewServiceInfoForClient()
	ordersServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return ordersServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return ordersServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return ordersServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrdersService"
	handlerType := (*orders.OrdersService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "orders",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func getOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(orders.GetOrdersReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orders.OrdersService).GetOrders(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetOrdersArgs:
		success, err := handler.(orders.OrdersService).GetOrders(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetOrdersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetOrdersArgs() interface{} {
	return &GetOrdersArgs{}
}

func newGetOrdersResult() interface{} {
	return &GetOrdersResult{}
}

type GetOrdersArgs struct {
	Req *orders.GetOrdersReq
}

func (p *GetOrdersArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(orders.GetOrdersReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetOrdersArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetOrdersArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetOrdersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetOrdersArgs) Unmarshal(in []byte) error {
	msg := new(orders.GetOrdersReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetOrdersArgs_Req_DEFAULT *orders.GetOrdersReq

func (p *GetOrdersArgs) GetReq() *orders.GetOrdersReq {
	if !p.IsSetReq() {
		return GetOrdersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetOrdersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetOrdersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetOrdersResult struct {
	Success *orders.GetOrdersResp
}

var GetOrdersResult_Success_DEFAULT *orders.GetOrdersResp

func (p *GetOrdersResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(orders.GetOrdersResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetOrdersResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetOrdersResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetOrdersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetOrdersResult) Unmarshal(in []byte) error {
	msg := new(orders.GetOrdersResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetOrdersResult) GetSuccess() *orders.GetOrdersResp {
	if !p.IsSetSuccess() {
		return GetOrdersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*orders.GetOrdersResp)
}

func (p *GetOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetOrdersResult) GetResult() interface{} {
	return p.Success
}

func addOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(orders.AddOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orders.OrdersService).AddOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddOrderArgs:
		success, err := handler.(orders.OrdersService).AddOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddOrderArgs() interface{} {
	return &AddOrderArgs{}
}

func newAddOrderResult() interface{} {
	return &AddOrderResult{}
}

type AddOrderArgs struct {
	Req *orders.AddOrderReq
}

func (p *AddOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(orders.AddOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddOrderArgs) Unmarshal(in []byte) error {
	msg := new(orders.AddOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddOrderArgs_Req_DEFAULT *orders.AddOrderReq

func (p *AddOrderArgs) GetReq() *orders.AddOrderReq {
	if !p.IsSetReq() {
		return AddOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddOrderResult struct {
	Success *orders.AddOrderResp
}

var AddOrderResult_Success_DEFAULT *orders.AddOrderResp

func (p *AddOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(orders.AddOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddOrderResult) Unmarshal(in []byte) error {
	msg := new(orders.AddOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddOrderResult) GetSuccess() *orders.AddOrderResp {
	if !p.IsSetSuccess() {
		return AddOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*orders.AddOrderResp)
}

func (p *AddOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddOrderResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetOrders(ctx context.Context, Req *orders.GetOrdersReq) (r *orders.GetOrdersResp, err error) {
	var _args GetOrdersArgs
	_args.Req = Req
	var _result GetOrdersResult
	if err = p.c.Call(ctx, "GetOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddOrder(ctx context.Context, Req *orders.AddOrderReq) (r *orders.AddOrderResp, err error) {
	var _args AddOrderArgs
	_args.Req = Req
	var _result AddOrderResult
	if err = p.c.Call(ctx, "AddOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
