// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderauthchangeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderproductputMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderprodectdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderauthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _centerMw() []app.HandlerFunc {
	// your code...
	return nil
}
