// Code generated by hertz generator.

package orders

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getordersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addorderMw() []app.HandlerFunc {
	// your code...
	return nil
}
